### PR TITLE
Feature/GAT-19

### PR DESCRIPTION
**Pull request by 121052**
Fixed indentation and added highlighting on legal moves when hovering

### CODE REVIEW

**Comment by uvNikita** [comment]
You've created pull request for master, it should be pull request to develop branch

**Comment by 121052** [comment]
A nice, thanks

**Comment by uvNikita** [comment]
Would be nice if it would be two commits: 1 fixing indentation and one that implements feature because now it's hard to see where is the actual code :) But we can keep it for this time.

**Comment by 121052** [comment]
Yeah, that is true. The new functions are onMouseoverSquare, onMouseoutSquare and the highlightSquare and removeHighlight

**Pull request merged**
